name: macOS

on:
  push:
    branches:
        - master
    paths-ignore:
    - 'docs/**'
    - '.github/workflows/**'
    - '!.github/workflows/test_macos.yml'
  pull_request:

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
   
    - name: Install gtest
      run: |
        brew install googletest
    - name: Install dependencies
      run: |
        # sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.15.pkg -target /
        brew install --cask xquartz
        brew install llvm@11 swig udunits openmotif maven
    - name: Test env var
        run: |
          echo ${CI}
          python3 print_ci_var.py

